#!/usr/bin/env python
# -*- coding: utf-8 -*-

import logging
import re
import os
from datetime import datetime

def main():
    """
    Move statements into directories ordered by their account number.

    eg.

    From:
        123456789 2014-05-06 foo bar baz.pdf

    To:
        123456789/2014-05-06 foo bar baz.pdf
    """
    files = os.listdir(u'.')
    rename_list = []
    
    for filename in files:
        match = re.match(ur'([0-9]+) ([0-9]{4}-[0-9]{2}-[0-9]{2} .*)', filename)
        if not match:
            continue

        account_number, new_filename = match.groups()

        new_path = os.path.join(account_number, new_filename)
        
        rename_list.append((filename, new_path))

    for from_path, to_path in rename_list:
        path_dir = os.path.dirname(to_path)
        if not os.path.isdir(path_dir):
            logging.info(u"mkdir {}".format(path_dir))
            os.makedirs(path_dir)
        
        logging.info(u"move {} => {}".format(from_path, to_path))
        os.rename(from_path, to_path)
        
if __name__ == '__main__':
    logging.basicConfig(format='%(asctime)s %(levelname)-8s %(message)s', level=logging.INFO)

    main()

