#!/usr/bin/env python
# -*- coding: utf-8 -*-

import logging
import re
import os
from datetime import datetime

def main():
    """
    Rename RBC statements to add a better date (and account number) into the filename.
    eg.

    From:
        123456789-2014Apr09-2014May08.pdf

    To:
        123456789 2014-05-08 123456789-2014Apr09-2014May08.pdf
    
    """
    files = os.listdir(u'.')
    rename_list = []
    
    for filename in files:
        match = re.match(ur'([0-9]+)-([0-9]{4}[A-Z][a-z][a-z][0-9]{2})-([0-9]{4}[A-Z][a-z][a-z][0-9]{2})\.pdf$', filename)
        if not match:
            continue

        account_number, from_date, to_date = match.groups()
        
        from_date = datetime.strptime(from_date, r'%Y%b%d')
        to_date = datetime.strptime(to_date, r'%Y%b%d')

        new_filename = u'{} {:%Y-%m-%d} {}'.format(account_number, to_date, filename)
        rename_list.append((filename, new_filename))

    for from_filename, to_filename in rename_list:
        logging.info(u"Rename {} => {}".format(from_filename, to_filename))
        os.rename(from_filename, to_filename)
        
if __name__ == '__main__':
    logging.basicConfig(format='%(asctime)s %(levelname)-8s %(message)s', level=logging.INFO)

    main()

